apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportaldeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      company: ngs
  template:
    metadata:
      name: jobportalpod
      labels:
        company: ngs
    spec:
      containers:
        - name: jobportalcontainer
          image: public.ecr.aws/q2v7l2n8/ganesh8195/ngs-jobportal:1.0.0-49
          ports:
            - containerPort: 9595
